name = "webresume-now"
main = ".open-next/worker.js"
compatibility_date = "2025-11-18"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
